"use client";

import type { ReactNode } from "react";
import { useRouter } from "next/navigation";
import { Building2, User } from "lucide-react";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { ReportStatusBadge } from "@/components/reports/report-status-badge";
import type { AccomplishmentsReport } from "@/lib/data/types";
import { STAGGER_ITEM_CLASS, staggerDelay } from "@/lib/stagger";
import { cn } from "@/lib/utils";

function initials(fullName: string) {
  return fullName
    .split(" ")
    .map((part) => part[0])
    .join("")
    .slice(0, 2)
    .toUpperCase();
}

function formatDate(value: string) {
  return new Date(value).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" });
}

function formatRange(start: string, end: string) {
  return start === end ? formatDate(start) : `${formatDate(start)} – ${formatDate(end)}`;
}

interface ReportsTableProps {
  reports: AccomplishmentsReport[];
  isLoading: boolean;
  emptyMessage: string;
  filters?: ReactNode;
}

export function ReportsTable({ reports, isLoading, emptyMessage, filters }: ReportsTableProps) {
  const router = useRouter();
  const sorted = [...reports].sort((a, b) => b.generatedAt.localeCompare(a.generatedAt));

  return (
    <Card className="min-w-0 overflow-hidden py-0">
      {filters && <div className="flex flex-wrap items-center gap-3 border-b bg-muted/40 p-4">{filters}</div>}
      <Table>
        <TableHeader>
          <TableRow>
            <TableHead className="font-mono text-xs tracking-wide text-muted-foreground uppercase">Subject</TableHead>
            <TableHead className="font-mono text-xs tracking-wide text-muted-foreground uppercase">Kind</TableHead>
            <TableHead className="font-mono text-xs tracking-wide text-muted-foreground uppercase">Range</TableHead>
            <TableHead className="font-mono text-xs tracking-wide text-muted-foreground uppercase">Status</TableHead>
            <TableHead className="font-mono text-xs tracking-wide text-muted-foreground uppercase">Generated by</TableHead>
            <TableHead className="font-mono text-xs tracking-wide text-muted-foreground uppercase">Generated</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          {!isLoading && sorted.length === 0 && (
            <TableRow>
              <TableCell colSpan={6} className="py-10 text-center text-sm text-muted-foreground">
                {emptyMessage}
              </TableCell>
            </TableRow>
          )}
          {sorted.map((report, i) => (
            <TableRow
              key={report.id}
              className={cn("cursor-pointer", STAGGER_ITEM_CLASS)}
              style={staggerDelay(i)}
              onClick={() => router.push(`/dashboard/reports/${report.id}`)}
            >
              <TableCell className="py-3 font-medium">
                <div className="flex items-center gap-2.5">
                  <Avatar size="sm" className="shrink-0">
                    <AvatarFallback className="text-[10px]">{initials(report.subjectLabel)}</AvatarFallback>
                  </Avatar>
                  {report.subjectLabel}
                </div>
              </TableCell>
              <TableCell className="py-3">
                <Badge variant="neutral" className="capitalize">
                  {report.kind === "person" ? <User /> : <Building2 />}
                  {report.kind}
                </Badge>
              </TableCell>
              <TableCell className="py-3 text-muted-foreground">{formatRange(report.rangeStart, report.rangeEnd)}</TableCell>
              <TableCell className="py-3">
                <ReportStatusBadge status={report.status} />
              </TableCell>
              <TableCell className="py-3 text-muted-foreground">{report.generatedByName}</TableCell>
              <TableCell className="py-3 text-muted-foreground">{formatDate(report.generatedAt)}</TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </Card>
  );
}
