import type { ReportRangeLabel } from "./accomplishments-report";

export type ClientReportStatus = "draft" | "finalized";

/** Where a line item's data came from — provenance only, never rendered. */
export type ClientReportLineItemSource = "daily-update" | "raw" | "manual";

/**
 * One dated, timed contribution to an activity. `details` is the one truly free-text field in this
 * whole report — every other field is either an ID, an enum, a number, or a snapshotted label. This
 * is also the ONLY place a name could ever leak into a client-facing report (someone's Daily Update
 * text, or a task title, mentioning a colleague by name) — see the generation notes in the mock
 * provider for how each `source` is drafted, and why the edit-before-finalize step is load-bearing.
 */
export interface ClientReportLineItem {
  id: string;
  /** YYYY-MM-DD. */
  date: string;
  minutes: number;
  details: string;
  source: ClientReportLineItemSource;
}

export interface ClientReportActivitySection {
  /** Null only for the "Other" catch-all (untagged work). */
  activityId: string | null;
  activityName: string;
  lineItems: ClientReportLineItem[];
}

/** A department section only ever appears here if it has ≥1 activity with ≥1 line item, or was added
 *  manually via "+ Add section" — there is no "every catalog department, ticked or not" walk like the
 *  internal Accomplishments Report does. Unworked departments simply don't exist in this array. */
export interface ClientReportDepartmentSection {
  /** Null only for the "Other" pseudo-department (untagged work has no real department). */
  departmentId: string | null;
  departmentName: string;
  activities: ClientReportActivitySection[];
}

/** Internal reviewer feedback — same shape/philosophy as AccomplishmentsReportComment. Staff-only:
 *  never rendered in print/export, since authorName is a staff member's name. */
export interface ClientReportComment {
  id: string;
  authorId: string;
  authorName: string;
  body: string;
  createdAt: string;
}

export type ClientReportHistoryEventType = "finalized" | "reopened" | "re-finalized";

/** Internal integrity log — same shape as AccomplishmentsReportHistoryEvent. Staff-only: never
 *  rendered in print/export, since actorName is a staff member's name. */
export interface ClientReportHistoryEvent {
  id: string;
  type: ClientReportHistoryEventType;
  actorId: string;
  actorName: string;
  createdAt: string;
}

/**
 * A client-facing accomplishments report — a stored snapshot document, generated per company for a
 * date range (daily/weekly/custom, same three-value `rangeLabel` the internal report uses). Deliberately
 * a separate type from `AccomplishmentsReport`, not a variant of it: the content shape is fundamentally
 * different (multiple dated, timed line items per activity here, vs. one done+detail line there), and
 * the audience/safety requirements are different (this one is meant to leave the building — no
 * employee name may ever appear in its rendered/exported form).
 *
 * `generatedById`/`generatedByName`/`comments`/`history` are internal record-keeping only — they
 * appear on the staff-only editing screen (mirroring the internal report's own "generated by" line
 * and integrity log) but are NEVER part of the printed/exported document. See ClientReportView,
 * ClientReportComments, and ClientReportHistory for where that boundary is enforced.
 */
export interface ClientReport {
  id: string;
  /**
   * The annual/contract Project this report is scoped to — the real reporting-period boundary
   * (Phase 9B). A Company can have several Projects over time (e.g. "Alderleaf Manufacturing
   * 2025-2026" and "...2026-2027"); Task/time evidence for a report is gathered by Project, never
   * by Company alone, so two overlapping annual contracts can never have their work mixed into one
   * report. `null` only on a legacy report generated before Phase 9B (Company-only at the time) —
   * that historical snapshot is never retroactively reassigned to a guessed Project.
   */
  projectId: string | null;
  companyId: string;
  companyLabel: string;
  brandId: string;
  brandLabel: string;
  rangeLabel: ReportRangeLabel;
  rangeStart: string;
  rangeEnd: string;
  status: ClientReportStatus;
  /** Only departments with ≥1 activity section — see ClientReportDepartmentSection's own note. */
  departments: ClientReportDepartmentSection[];
  comments: ClientReportComment[];
  history: ClientReportHistoryEvent[];
  generatedById: string;
  generatedByName: string;
  generatedAt: string;
  finalizedAt: string | null;
  deletedAt: string | null;
  createdAt: string;
  updatedAt: string;
}
