"use client";

import type { ReactNode } from "react";
import { useRouter } from "next/navigation";
import { Building2, ChevronRight } from "lucide-react";
import { Card } from "@/components/ui/card";
import { ContainedIcon } from "@/components/ui/contained-icon";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { ClientReportStatusBadge } from "@/components/client-reports/client-report-status-badge";
import type { ClientReport } from "@/lib/data/types";
import { STAGGER_ITEM_CLASS, staggerDelay } from "@/lib/stagger";
import { cn } from "@/lib/utils";

function formatDate(value: string) {
  return new Date(value).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" });
}

function formatRange(start: string, end: string) {
  return start === end ? formatDate(start) : `${formatDate(start)} – ${formatDate(end)}`;
}

interface ClientReportsTableProps {
  reports: ClientReport[];
  /** Project id → name, from the same `useProjects()` list already used elsewhere (no new data
   * access) — a report is identified by Client + Project + Period, not by who generated it. */
  projectNameById: Map<string, string>;
  isLoading: boolean;
  emptyMessage: string;
  filters?: ReactNode;
}

/**
 * "Recent Reports" — Phase 11D: a report's primary identity is Client + Project + Period, never the
 * generator or its lifecycle status. Status stays visible as a small secondary badge (backend
 * Draft/Finalized semantics are real and untouched), never the organizing column. "Generated by" is
 * deliberately NOT a column here anymore — that identity remains available where it belongs
 * (the report detail page's own internal history/metadata), not as a primary label on the normal
 * list every role sees.
 */
export function ClientReportsTable({ reports, projectNameById, isLoading, emptyMessage, filters }: ClientReportsTableProps) {
  const router = useRouter();
  const sorted = [...reports].sort((a, b) => b.generatedAt.localeCompare(a.generatedAt));

  return (
    <Card className="min-w-0 overflow-hidden py-0">
      {filters && <div className="flex flex-wrap items-center gap-3 border-b bg-muted/40 p-4">{filters}</div>}
      <Table>
        <TableHeader>
          <TableRow>
            <TableHead className="font-mono text-xs tracking-wide text-muted-foreground uppercase">Client</TableHead>
            <TableHead className="font-mono text-xs tracking-wide text-muted-foreground uppercase">Project</TableHead>
            <TableHead className="font-mono text-xs tracking-wide text-muted-foreground uppercase">Period</TableHead>
            <TableHead className="font-mono text-xs tracking-wide text-muted-foreground uppercase">Generated</TableHead>
            <TableHead className="font-mono text-xs tracking-wide text-muted-foreground uppercase">Status</TableHead>
            <TableHead className="font-mono text-xs tracking-wide text-muted-foreground uppercase" />
          </TableRow>
        </TableHeader>
        <TableBody>
          {!isLoading && sorted.length === 0 && (
            <TableRow>
              <TableCell colSpan={6} className="py-10 text-center text-sm text-muted-foreground">
                {emptyMessage}
              </TableCell>
            </TableRow>
          )}
          {sorted.map((report, i) => (
            <TableRow
              key={report.id}
              className={cn("cursor-pointer", STAGGER_ITEM_CLASS)}
              style={staggerDelay(i)}
              onClick={() => router.push(`/dashboard/reports/client/${report.id}`)}
            >
              <TableCell className="py-3 font-medium">
                <div className="flex items-center gap-2.5">
                  <ContainedIcon size="sm" tone="active">
                    <Building2 />
                  </ContainedIcon>
                  {report.companyLabel}
                </div>
              </TableCell>
              <TableCell className="py-3 text-muted-foreground">
                {report.projectId ? (projectNameById.get(report.projectId) ?? "—") : "—"}
              </TableCell>
              <TableCell className="py-3 text-muted-foreground">{formatRange(report.rangeStart, report.rangeEnd)}</TableCell>
              <TableCell className="py-3 text-muted-foreground">{formatDate(report.generatedAt)}</TableCell>
              <TableCell className="py-3">
                <ClientReportStatusBadge status={report.status} />
              </TableCell>
              <TableCell className="py-3 text-muted-foreground">
                <ChevronRight className="size-4" aria-hidden="true" />
              </TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </Card>
  );
}
