"use client";

import type { ReactNode } from "react";
import { useRouter } from "next/navigation";
import { Building2, ChevronRight } from "lucide-react";
import { Card } from "@/components/ui/card";
import { ContainedIcon } from "@/components/ui/contained-icon";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import type { ClientReport } from "@/lib/data/types";
import { STAGGER_ITEM_CLASS, staggerDelay } from "@/lib/stagger";
import { cn } from "@/lib/utils";

function formatDate(value: string) {
  return new Date(value).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" });
}

function formatRange(start: string, end: string) {
  return start === end ? formatDate(start) : `${formatDate(start)} – ${formatDate(end)}`;
}

interface ClientReportsTableProps {
  reports: ClientReport[];
  isLoading: boolean;
  emptyMessage: string;
  filters?: ReactNode;
}

/**
 * "Recent Reports" — Phase 12A: a report's user-facing identity is Client + Reporting Period only.
 * "Generated by" is deliberately NOT a column here — that identity remains available where it
 * belongs (the report detail page's own internal history/metadata), not as a primary label on the
 * normal list every role sees. Lifecycle status (Draft/Finalized) is likewise not presented here —
 * the backend lifecycle is real and untouched (see permissions.ts/client-report provider), it's
 * simply no longer a visible product concept; a reviewer opens a report and its own detail page
 * exposes exactly the actions they're still authorized to take (Save/Finalize disappear on their own
 * once a report is finalized, with no status label needed to explain why). "Project" is likewise not
 * a column — the backend remains Project-scoped (see the generation dialog), it's just not a
 * separate thing the employee needs to think about here.
 */
export function ClientReportsTable({ reports, isLoading, emptyMessage, filters }: ClientReportsTableProps) {
  const router = useRouter();
  const sorted = [...reports].sort((a, b) => b.generatedAt.localeCompare(a.generatedAt));

  return (
    <Card className="min-w-0 overflow-hidden py-0">
      {filters && <div className="flex flex-wrap items-center gap-3 border-b bg-muted/40 p-4">{filters}</div>}
      <Table>
        <TableHeader>
          <TableRow>
            <TableHead className="font-mono text-xs tracking-wide text-muted-foreground uppercase">Client</TableHead>
            <TableHead className="font-mono text-xs tracking-wide text-muted-foreground uppercase">Reporting Period</TableHead>
            <TableHead className="font-mono text-xs tracking-wide text-muted-foreground uppercase">Generated</TableHead>
            <TableHead className="font-mono text-xs tracking-wide text-muted-foreground uppercase">Open</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          {!isLoading && sorted.length === 0 && (
            <TableRow>
              <TableCell colSpan={4} className="py-10 text-center text-sm text-muted-foreground">
                {emptyMessage}
              </TableCell>
            </TableRow>
          )}
          {sorted.map((report, i) => (
            <TableRow
              key={report.id}
              className={cn("cursor-pointer", STAGGER_ITEM_CLASS)}
              style={staggerDelay(i)}
              onClick={() => router.push(`/dashboard/reports/client/${report.id}`)}
            >
              <TableCell className="py-3 font-medium">
                <div className="flex items-center gap-2.5">
                  <ContainedIcon size="sm" tone="active">
                    <Building2 />
                  </ContainedIcon>
                  {report.companyLabel}
                </div>
              </TableCell>
              <TableCell className="py-3 text-muted-foreground">{formatRange(report.rangeStart, report.rangeEnd)}</TableCell>
              <TableCell className="py-3 text-muted-foreground">{formatDate(report.generatedAt)}</TableCell>
              <TableCell className="py-3 text-muted-foreground">
                <ChevronRight className="size-4" aria-hidden="true" />
              </TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </Card>
  );
}
